name: snaprecipes
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.4
  provider: ^6.0.0
  http: ^1.2.0
  sqflite: ^2.3.0
  path: ^1.8.3
  share_plus: ^10.0.0
  pdf: ^3.10.0
  printing: ^5.11.0
  path_provider: ^2.1.0
  connectivity_plus: ^6.0.0
  
  # Voltando para o ML Kit (Google)
  google_mlkit_image_labeling: ^0.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Assets (Mantemos a pasta, embora ML Kit padrão não use o tflite local)
  assets:
    - assets/models/
